package com.example.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CITY_WEATHER_TYPE".
*/
public class CityWeatherTypeDao extends AbstractDao<CityWeatherType, Long> {

    public static final String TABLENAME = "CITY_WEATHER_TYPE";

    /**
     * Properties of entity CityWeatherType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property WeatherType = new Property(1, String.class, "weatherType", false, "WEATHER_TYPE");
        public final static Property SmallImage = new Property(2, String.class, "smallImage", false, "SMALL_IMAGE");
        public final static Property BigImage = new Property(3, String.class, "bigImage", false, "BIG_IMAGE");
    }


    public CityWeatherTypeDao(DaoConfig config) {
        super(config);
    }
    
    public CityWeatherTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CITY_WEATHER_TYPE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"WEATHER_TYPE\" TEXT NOT NULL ," + // 1: weatherType
                "\"SMALL_IMAGE\" TEXT NOT NULL ," + // 2: smallImage
                "\"BIG_IMAGE\" TEXT NOT NULL );"); // 3: bigImage
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CITY_WEATHER_TYPE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CityWeatherType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getWeatherType());
        stmt.bindString(3, entity.getSmallImage());
        stmt.bindString(4, entity.getBigImage());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CityWeatherType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getWeatherType());
        stmt.bindString(3, entity.getSmallImage());
        stmt.bindString(4, entity.getBigImage());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CityWeatherType readEntity(Cursor cursor, int offset) {
        CityWeatherType entity = new CityWeatherType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // weatherType
            cursor.getString(offset + 2), // smallImage
            cursor.getString(offset + 3) // bigImage
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CityWeatherType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWeatherType(cursor.getString(offset + 1));
        entity.setSmallImage(cursor.getString(offset + 2));
        entity.setBigImage(cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CityWeatherType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CityWeatherType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CityWeatherType entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
